/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Accueil } from "./Accueil";
import { AccueilCountArgs } from "./AccueilCountArgs";
import { AccueilFindManyArgs } from "./AccueilFindManyArgs";
import { AccueilFindUniqueArgs } from "./AccueilFindUniqueArgs";
import { DeleteAccueilArgs } from "./DeleteAccueilArgs";
import { AccueilService } from "../accueil.service";
@graphql.Resolver(() => Accueil)
export class AccueilResolverBase {
  constructor(protected readonly service: AccueilService) {}

  async _accueilsMeta(
    @graphql.Args() args: AccueilCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Accueil])
  async accueils(
    @graphql.Args() args: AccueilFindManyArgs
  ): Promise<Accueil[]> {
    return this.service.accueils(args);
  }

  @graphql.Query(() => Accueil, { nullable: true })
  async accueil(
    @graphql.Args() args: AccueilFindUniqueArgs
  ): Promise<Accueil | null> {
    const result = await this.service.accueil(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Accueil)
  async deleteAccueil(
    @graphql.Args() args: DeleteAccueilArgs
  ): Promise<Accueil | null> {
    try {
      return await this.service.deleteAccueil(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
