/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Voyages } from "./Voyages";
import { VoyagesCountArgs } from "./VoyagesCountArgs";
import { VoyagesFindManyArgs } from "./VoyagesFindManyArgs";
import { VoyagesFindUniqueArgs } from "./VoyagesFindUniqueArgs";
import { DeleteVoyagesArgs } from "./DeleteVoyagesArgs";
import { VoyagesService } from "../voyages.service";
@graphql.Resolver(() => Voyages)
export class VoyagesResolverBase {
  constructor(protected readonly service: VoyagesService) {}

  async _voyagesItemsMeta(
    @graphql.Args() args: VoyagesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Voyages])
  async voyagesItems(
    @graphql.Args() args: VoyagesFindManyArgs
  ): Promise<Voyages[]> {
    return this.service.voyagesItems(args);
  }

  @graphql.Query(() => Voyages, { nullable: true })
  async voyages(
    @graphql.Args() args: VoyagesFindUniqueArgs
  ): Promise<Voyages | null> {
    const result = await this.service.voyages(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Voyages)
  async deleteVoyages(
    @graphql.Args() args: DeleteVoyagesArgs
  ): Promise<Voyages | null> {
    try {
      return await this.service.deleteVoyages(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
